// Water Element Techniques
export const WATER_FIGHTING_TECHNIQUES = [
  // Movement Techniques
  {
    name: "Water Surfing Art",
    grade: 1,
    type: "Water",
    description: "A basic water element movement technique",
    stats: { hp: 0, sp: 0, str: 0.1, agl: 0.3 },
  },
  {
    name: "Water Dash Technique",
    grade: 2,
    type: "Water",
    description: "A decent water element movement technique",
    stats: { hp: 0, sp: 0.1, str: 0.2, agl: 0.5 },
  },
  {
    name: "Aqua Glide",
    grade: 3,
    type: "Water",
    description: "An advanced water element movement technique",
    stats: { hp: 0, sp: 0.2, str: 0.3, agl: 0.7 },
  },
  {
    name: "Tidal Wave Rush",
    grade: 4,
    type: "Water",
    description: "An expert water element movement technique",
    stats: { hp: 0, sp: 0.3, str: 0.4, agl: 0.9 },
  },
  {
    name: "Oceanic Vortex Sprint",
    grade: 5,
    type: "Water",
    description: "A master-level water element movement technique",
    stats: { hp: 0, sp: 0.4, str: 0.5, agl: 1.1 },
  },
  // Killing Moves
  {
    name: "Ice Dagger Slash",
    grade: 1,
    type: "Water",
    description: "A basic water element killing move",
    stats: { hp: 0.1, sp: 0, str: 0.2, agl: 0.1 },
  },
  {
    name: "Frost Blade Assault",
    grade: 2,
    type: "Water",
    description: "A decent water element killing move",
    stats: { hp: 0.2, sp: 0.1, str: 0.3, agl: 0.2 },
  },
  {
    name: "Glacial Spike Burst",
    grade: 3,
    type: "Water",
    description: "An advanced water element killing move",
    stats: { hp: 0.3, sp: 0.2, str: 0.4, agl: 0.3 },
  },
  {
    name: "Abyssal Tsunami Strike",
    grade: 4,
    type: "Water",
    description: "An expert water element killing move",
    stats: { hp: 0.4, sp: 0.3, str: 0.5, agl: 0.4 },
  },
  {
    name: "Celestial Rainfall Annihilation",
    grade: 5,
    type: "Water",
    description: "A master-level water element killing move",
    stats: { hp: 0.5, sp: 0.4, str: 0.6, agl: 0.5 },
  },
  // Body Refinement
  {
    name: "Ice Skin Forging",
    grade: 1,
    type: "Water",
    description: "A basic water element body forging art",
    stats: { hp: 0.3, sp: 0, str: 0.1, agl: 0 },
  },
  {
    name: "Frost Armor Crafting",
    grade: 2,
    type: "Water",
    description: "A decent water element body forging art",
    stats: { hp: 0.4, sp: 0.1, str: 0.2, agl: 0.1 },
  },
  {
    name: "Glacial Body Sculpting",
    grade: 3,
    type: "Water",
    description: "An advanced water element body forging art",
    stats: { hp: 0.5, sp: 0.2, str: 0.3, agl: 0.2 },
  },
  {
    name: "Abyssal Body Reinforcement",
    grade: 4,
    type: "Water",
    description: "An expert water element body forging art",
    stats: { hp: 0.6, sp: 0.3, str: 0.4, agl: 0.3 },
  },
  {
    name: "Celestial Body Ascension",
    grade: 5,
    type: "Water",
    description: "A master-level water element body forging art",
    stats: { hp: 0.7, sp: 0.4, str: 0.5, agl: 0.4 },
  },
  // Mind Techniques
  {
    name: "Mind Of Flowing Water",
    grade: 2,
    type: "Water",
    description: "A decent water element spirit enhancing art",
    stats: { hp: 0, sp: 0.6, str: 0, agl: 0.2 },
  },
  {
    name: "Aqua Mindfulness",
    grade: 3,
    type: "Water",
    description: "An advanced water element spirit enhancing art",
    stats: { hp: 0, sp: 0.8, str: 0, agl: 0.3 },
  },
  {
    name: "Tidal Wave Focus",
    grade: 4,
    type: "Water",
    description: "An expert water element spirit enhancing art",
    stats: { hp: 0, sp: 1, str: 0, agl: 0.4 },
  },
  {
    name: "Oceanic Vortex Meditation",
    grade: 5,
    type: "Water",
    description: "A master-level water element spirit enhancing art",
    stats: { hp: 0, sp: 1.2, str: 0, agl: 0.5 },
  },
];

// Fire Element Techniques
export const FIRE_FIGHTING_TECHNIQUES = [
  // Movement Techniques
  {
    name: "Flame Step",
    grade: 1,
    type: "Fire",
    description: "A basic fire element movement technique",
    stats: { hp: 0, sp: 0, str: 0.1, agl: 0.3 },
  },
  {
    name: "Blazing Dash",
    grade: 2,
    type: "Fire",
    description: "A decent fire element movement technique",
    stats: { hp: 0, sp: 0.1, str: 0.2, agl: 0.5 },
  },
  {
    name: "Inferno Glide",
    grade: 3,
    type: "Fire",
    description: "An advanced fire element movement technique",
    stats: { hp: 0, sp: 0.2, str: 0.3, agl: 0.7 },
  },
  {
    name: "Magma Rush",
    grade: 4,
    type: "Fire",
    description: "An expert fire element movement technique",
    stats: { hp: 0, sp: 0.3, str: 0.4, agl: 0.9 },
  },
  {
    name: "Phoenix Flight",
    grade: 5,
    type: "Fire",
    description: "A master-level fire element movement technique",
    stats: { hp: 0, sp: 0.4, str: 0.5, agl: 1.1 },
  },
  // Killing Moves
  {
    name: "Ember Slash",
    grade: 1,
    type: "Fire",
    description: "A basic fire element killing move",
    stats: { hp: 0.1, sp: 0, str: 0.2, agl: 0.1 },
  },
  {
    name: "Flame Sword",
    grade: 2,
    type: "Fire",
    description: "A decent fire element killing move",
    stats: { hp: 0.2, sp: 0.1, str: 0.3, agl: 0.2 },
  },
  {
    name: "Inferno Burst",
    grade: 3,
    type: "Fire",
    description: "An advanced fire element killing move",
    stats: { hp: 0.3, sp: 0.2, str: 0.4, agl: 0.3 },
  },
  {
    name: "Magma Eruption",
    grade: 4,
    type: "Fire",
    description: "An expert fire element killing move",
    stats: { hp: 0.4, sp: 0.3, str: 0.5, agl: 0.4 },
  },
  {
    name: "Phoenix Blaze",
    grade: 5,
    type: "Fire",
    description: "A master-level fire element killing move",
    stats: { hp: 0.5, sp: 0.4, str: 0.6, agl: 0.5 },
  },
  // Body Refinement
  {
    name: "Ember Skin",
    grade: 1,
    type: "Fire",
    description: "A basic fire element body forging art",
    stats: { hp: 0.3, sp: 0, str: 0.1, agl: 0 },
  },
  {
    name: "Flame Armor",
    grade: 2,
    type: "Fire",
    description: "A decent fire element body forging art",
    stats: { hp: 0.4, sp: 0.1, str: 0.2, agl: 0.1 },
  },
  {
    name: "Inferno Body",
    grade: 3,
    type: "Fire",
    description: "An advanced fire element body forging art",
    stats: { hp: 0.5, sp: 0.2, str: 0.3, agl: 0.2 },
  },
  {
    name: "Magma Core",
    grade: 4,
    type: "Fire",
    description: "An expert fire element body forging art",
    stats: { hp: 0.6, sp: 0.3, str: 0.4, agl: 0.3 },
  },
  {
    name: "Phoenix Rebirth",
    grade: 5,
    type: "Fire",
    description: "A master-level fire element body forging art",
    stats: { hp: 0.7, sp: 0.4, str: 0.5, agl: 0.4 },
  },
  // Mind Techniques
  {
    name: "Ember Mind",
    grade: 1,
    type: "Fire",
    description: "A basic fire element spirit enhancing art",
    stats: { hp: 0, sp: 0.4, str: 0, agl: 0.1 },
  },
  {
    name: "Flame Focus",
    grade: 2,
    type: "Fire",
    description: "A decent fire element spirit enhancing art",
    stats: { hp: 0, sp: 0.6, str: 0, agl: 0.2 },
  },
  {
    name: "Inferno Meditation",
    grade: 3,
    type: "Fire",
    description: "An advanced fire element spirit enhancing art",
    stats: { hp: 0, sp: 0.8, str: 0, agl: 0.3 },
  },
  {
    name: "Magma Concentration",
    grade: 4,
    type: "Fire",
    description: "An expert fire element spirit enhancing art",
    stats: { hp: 0, sp: 1, str: 0, agl: 0.4 },
  },
  {
    name: "Phoenix Enlightenment",
    grade: 5,
    type: "Fire",
    description: "A master-level fire element spirit enhancing art",
    stats: { hp: 0, sp: 1.2, str: 0, agl: 0.5 },
  },
];

// Earth Element Techniques
export const EARTH_FIGHTING_TECHNIQUES = [
  // Movement Techniques
  {
    name: "Stone Step",
    grade: 1,
    type: "Earth",
    description: "A basic earth element movement technique",
    stats: { hp: 0, sp: 0, str: 0.1, agl: 0.3 },
  },
  {
    name: "Rock Slide",
    grade: 2,
    type: "Earth",
    description: "A decent earth element movement technique",
    stats: { hp: 0, sp: 0.1, str: 0.2, agl: 0.5 },
  },
  {
    name: "Boulder Dash",
    grade: 3,
    type: "Earth",
    description: "An advanced earth element movement technique",
    stats: { hp: 0, sp: 0.2, str: 0.3, agl: 0.7 },
  },
  {
    name: "Mountain Leap",
    grade: 4,
    type: "Earth",
    description: "An expert earth element movement technique",
    stats: { hp: 0, sp: 0.3, str: 0.4, agl: 0.9 },
  },
  {
    name: "Tectonic Shift",
    grade: 5,
    type: "Earth",
    description: "A master-level earth element movement technique",
    stats: { hp: 0, sp: 0.4, str: 0.5, agl: 1.1 },
  },
  // Killing Moves
  {
    name: "Stone Fist",
    grade: 1,
    type: "Earth",
    description: "A basic earth element killing move",
    stats: { hp: 0.1, sp: 0, str: 0.2, agl: 0.1 },
  },
  {
    name: "Rock Smash",
    grade: 2,
    type: "Earth",
    description: "A decent earth element killing move",
    stats: { hp: 0.2, sp: 0.1, str: 0.3, agl: 0.2 },
  },
  {
    name: "Boulder Crush",
    grade: 3,
    type: "Earth",
    description: "An advanced earth element killing move",
    stats: { hp: 0.3, sp: 0.2, str: 0.4, agl: 0.3 },
  },
  {
    name: "Mountain Strike",
    grade: 4,
    type: "Earth",
    description: "An expert earth element killing move",
    stats: { hp: 0.4, sp: 0.3, str: 0.5, agl: 0.4 },
  },
  {
    name: "Tectonic Rupture",
    grade: 5,
    type: "Earth",
    description: "A master-level earth element killing move",
    stats: { hp: 0.5, sp: 0.4, str: 0.6, agl: 0.5 },
  },
  // Body Refinement
  {
    name: "Stone Skin",
    grade: 1,
    type: "Earth",
    description: "A basic earth element body forging art",
    stats: { hp: 0.3, sp: 0, str: 0.1, agl: 0 },
  },
  {
    name: "Rock Armor",
    grade: 2,
    type: "Earth",
    description: "A decent earth element body forging art",
    stats: { hp: 0.4, sp: 0.1, str: 0.2, agl: 0.1 },
  },
  {
    name: "Boulder Body",
    grade: 3,
    type: "Earth",
    description: "An advanced earth element body forging art",
    stats: { hp: 0.5, sp: 0.2, str: 0.3, agl: 0.2 },
  },
  {
    name: "Mountain Core",
    grade: 4,
    type: "Earth",
    description: "An expert earth element body forging art",
    stats: { hp: 0.6, sp: 0.3, str: 0.4, agl: 0.3 },
  },
  {
    name: "Tectonic Essence",
    grade: 5,
    type: "Earth",
    description: "A master-level earth element body forging art",
    stats: { hp: 0.7, sp: 0.4, str: 0.5, agl: 0.4 },
  },
  // Mind Techniques
  {
    name: "Stone Mind",
    grade: 1,
    type: "Earth",
    description: "A basic earth element spirit enhancing art",
    stats: { hp: 0, sp: 0.4, str: 0, agl: 0.1 },
  },
  {
    name: "Rock Focus",
    grade: 2,
    type: "Earth",
    description: "A decent earth element spirit enhancing art",
    stats: { hp: 0, sp: 0.6, str: 0, agl: 0.2 },
  },
  {
    name: "Boulder Meditation",
    grade: 3,
    type: "Earth",
    description: "An advanced earth element spirit enhancing art",
    stats: { hp: 0, sp: 0.8, str: 0, agl: 0.3 },
  },
  {
    name: "Mountain Concentration",
    grade: 4,
    type: "Earth",
    description: "An expert earth element spirit enhancing art",
    stats: { hp: 0, sp: 1, str: 0, agl: 0.4 },
  },
  {
    name: "Tectonic Enlightenment",
    grade: 5,
    type: "Earth",
    description: "A master-level earth element spirit enhancing art",
    stats: { hp: 0, sp: 1.2, str: 0, agl: 0.5 },
  },
];

// Metal Element Techniques
export const METAL_FIGHTING_TECHNIQUES = [
  // Movement Techniques
  {
    name: "Metal Glide",
    grade: 1,
    type: "Metal",
    description: "A basic metal element movement technique",
    stats: { hp: 0, sp: 0, str: 0.1, agl: 0.3 },
  },
  {
    name: "Steel Dash",
    grade: 2,
    type: "Metal",
    description: "A decent metal element movement technique",
    stats: { hp: 0, sp: 0.1, str: 0.2, agl: 0.5 },
  },
  {
    name: "Iron Flight",
    grade: 3,
    type: "Metal",
    description: "An advanced metal element movement technique",
    stats: { hp: 0, sp: 0.2, str: 0.3, agl: 0.7 },
  },
  {
    name: "Alloy Leap",
    grade: 4,
    type: "Metal",
    description: "An expert metal element movement technique",
    stats: { hp: 0, sp: 0.3, str: 0.4, agl: 0.9 },
  },
  {
    name: "Titanium Warp",
    grade: 5,
    type: "Metal",
    description: "A master-level metal element movement technique",
    stats: { hp: 0, sp: 0.4, str: 0.5, agl: 1.1 },
  },
  // Killing Moves
  {
    name: "Blade Slash",
    grade: 1,
    type: "Metal",
    description: "A basic metal element killing move",
    stats: { hp: 0.1, sp: 0, str: 0.2, agl: 0.1 },
  },
  {
    name: "Steel Strike",
    grade: 2,
    type: "Metal",
    description: "A decent metal element killing move",
    stats: { hp: 0.2, sp: 0.1, str: 0.3, agl: 0.2 },
  },
  {
    name: "Iron Fist",
    grade: 3,
    type: "Metal",
    description: "An advanced metal element killing move",
    stats: { hp: 0.3, sp: 0.2, str: 0.4, agl: 0.3 },
  },
  {
    name: "Alloy Blade",
    grade: 4,
    type: "Metal",
    description: "An expert metal element killing move",
    stats: { hp: 0.4, sp: 0.3, str: 0.5, agl: 0.4 },
  },
  {
    name: "Titanium Smash",
    grade: 5,
    type: "Metal",
    description: "A master-level metal element killing move",
    stats: { hp: 0.5, sp: 0.4, str: 0.6, agl: 0.5 },
  },
  // Body Refinement
  {
    name: "Iron Skin",
    grade: 1,
    type: "Metal",
    description: "A basic metal element body forging art",
    stats: { hp: 0.3, sp: 0, str: 0.1, agl: 0 },
  },
  {
    name: "Steel Armor",
    grade: 2,
    type: "Metal",
    description: "A decent metal element body forging art",
    stats: { hp: 0.4, sp: 0.1, str: 0.2, agl: 0.1 },
  },
  {
    name: "Alloy Body",
    grade: 3,
    type: "Metal",
    description: "An advanced metal element body forging art",
    stats: { hp: 0.5, sp: 0.2, str: 0.3, agl: 0.2 },
  },
  {
    name: "Titanium Core",
    grade: 4,
    type: "Metal",
    description: "An expert metal element body forging art",
    stats: { hp: 0.6, sp: 0.3, str: 0.4, agl: 0.3 },
  },
  {
    name: "Adamantium Essence",
    grade: 5,
    type: "Metal",
    description: "A master-level metal element body forging art",
    stats: { hp: 0.7, sp: 0.4, str: 0.5, agl: 0.4 },
  },
  // Mind Techniques
  {
    name: "Metal Focus",
    grade: 1,
    type: "Metal",
    description: "A basic metal element spirit enhancing art",
    stats: { hp: 0, sp: 0.4, str: 0, agl: 0.1 },
  },
  {
    name: "Steel Mind",
    grade: 2,
    type: "Metal",
    description: "A decent metal element spirit enhancing art",
    stats: { hp: 0, sp: 0.6, str: 0, agl: 0.2 },
  },
  {
    name: "Iron Will",
    grade: 3,
    type: "Metal",
    description: "An advanced metal element spirit enhancing art",
    stats: { hp: 0, sp: 0.8, str: 0, agl: 0.3 },
  },
  {
    name: "Alloy Concentration",
    grade: 4,
    type: "Metal",
    description: "An expert metal element spirit enhancing art",
    stats: { hp: 0, sp: 1, str: 0, agl: 0.4 },
  },
  {
    name: "Titanium Enlightenment",
    grade: 5,
    type: "Metal",
    description: "A master-level metal element spirit enhancing art",
    stats: { hp: 0, sp: 1.2, str: 0, agl: 0.5 },
  },
];

// Wood Element Techniques
export const WOOD_FIGHTING_TECHNIQUES = [
  // Movement Techniques
  {
    name: "Leaf Glide",
    grade: 1,
    type: "Wood",
    description: "A basic wood element movement technique",
    stats: { hp: 0, sp: 0, str: 0.1, agl: 0.3 },
  },
  {
    name: "Vine Swing",
    grade: 2,
    type: "Wood",
    description: "A decent wood element movement technique",
    stats: { hp: 0, sp: 0.1, str: 0.2, agl: 0.5 },
  },
  {
    name: "Tree Leap",
    grade: 3,
    type: "Wood",
    description: "An advanced wood element movement technique",
    stats: { hp: 0, sp: 0.2, str: 0.3, agl: 0.7 },
  },
  {
    name: "Forest Dash",
    grade: 4,
    type: "Wood",
    description: "An expert wood element movement technique",
    stats: { hp: 0, sp: 0.3, str: 0.4, agl: 0.9 },
  },
  {
    name: "Woodland Warp",
    grade: 5,
    type: "Wood",
    description: "A master-level wood element movement technique",
    stats: { hp: 0, sp: 0.4, str: 0.5, agl: 1.1 },
  },
  // Killing Moves
  {
    name: "Leaf Blade",
    grade: 1,
    type: "Wood",
    description: "A basic wood element killing move",
    stats: { hp: 0.1, sp: 0, str: 0.2, agl: 0.1 },
  },
  {
    name: "Vine Whip",
    grade: 2,
    type: "Wood",
    description: "A decent wood element killing move",
    stats: { hp: 0.2, sp: 0.1, str: 0.3, agl: 0.2 },
  },
  {
    name: "Branch Strike",
    grade: 3,
    type: "Wood",
    description: "An advanced wood element killing move",
    stats: { hp: 0.3, sp: 0.2, str: 0.4, agl: 0.3 },
  },
  {
    name: "Root Grasp",
    grade: 4,
    type: "Wood",
    description: "An expert wood element killing move",
    stats: { hp: 0.4, sp: 0.3, str: 0.5, agl: 0.4 },
  },
  {
    name: "Tree Smash",
    grade: 5,
    type: "Wood",
    description: "A master-level wood element killing move",
    stats: { hp: 0.5, sp: 0.4, str: 0.6, agl: 0.5 },
  },
  // Body Refinement
  {
    name: "Leaf Skin",
    grade: 1,
    type: "Wood",
    description: "A basic wood element body forging art",
    stats: { hp: 0.3, sp: 0, str: 0.1, agl: 0 },
  },
  {
    name: "Vine Armor",
    grade: 2,
    type: "Wood",
    description: "A decent wood element body forging art",
    stats: { hp: 0.4, sp: 0.1, str: 0.2, agl: 0.1 },
  },
  {
    name: "Bark Body",
    grade: 3,
    type: "Wood",
    description: "An advanced wood element body forging art",
    stats: { hp: 0.5, sp: 0.2, str: 0.3, agl: 0.2 },
  },
  {
    name: "Tree Core",
    grade: 4,
    type: "Wood",
    description: "An expert wood element body forging art",
    stats: { hp: 0.6, sp: 0.3, str: 0.4, agl: 0.3 },
  },
  {
    name: "Forest Essence",
    grade: 5,
    type: "Wood",
    description: "A master-level wood element body forging art",
    stats: { hp: 0.7, sp: 0.4, str: 0.5, agl: 0.4 },
  },
  // Mind Techniques
  {
    name: "Leaf Focus",
    grade: 1,
    type: "Wood",
    description: "A basic wood element spirit enhancing art",
    stats: { hp: 0, sp: 0.4, str: 0, agl: 0.1 },
  },
  {
    name: "Vine Mind",
    grade: 2,
    type: "Wood",
    description: "A decent wood element spirit enhancing art",
    stats: { hp: 0, sp: 0.6, str: 0, agl: 0.2 },
  },
  {
    name: "Tree Wisdom",
    grade: 3,
    type: "Wood",
    description: "An advanced wood element spirit enhancing art",
    stats: { hp: 0, sp: 0.8, str: 0, agl: 0.3 },
  },
  {
    name: "Forest Meditation",
    grade: 4,
    type: "Wood",
    description: "An expert wood element spirit enhancing art",
    stats: { hp: 0, sp: 1, str: 0, agl: 0.4 },
  },
  {
    name: "Woodland Enlightenment",
    grade: 5,
    type: "Wood",
    description: "A master-level wood element spirit enhancing art",
    stats: { hp: 0, sp: 1.2, str: 0, agl: 0.5 },
  },
];

// Air Element Techniques
export const AIR_FIGHTING_TECHNIQUES = [
  // Movement Techniques
  {
    name: "Wind Glide",
    grade: 1,
    type: "Air",
    description: "A basic air element movement technique",
    stats: { hp: 0, sp: 0, str: 0.1, agl: 0.3 },
  },
  {
    name: "Gale Dash",
    grade: 2,
    type: "Air",
    description: "A decent air element movement technique",
    stats: { hp: 0, sp: 0.1, str: 0.2, agl: 0.5 },
  },
  {
    name: "Tornado Leap",
    grade: 3,
    type: "Air",
    description: "An advanced air element movement technique",
    stats: { hp: 0, sp: 0.2, str: 0.3, agl: 0.7 },
  },
  {
    name: "Sky Soar",
    grade: 4,
    type: "Air",
    description: "An expert air element movement technique",
    stats: { hp: 0, sp: 0.3, str: 0.4, agl: 0.9 },
  },
  {
    name: "Cloud Drift",
    grade: 5,
    type: "Air",
    description: "A master-level air element movement technique",
    stats: { hp: 0, sp: 0.4, str: 0.5, agl: 1.1 },
  },
  // Killing Moves
  {
    name: "Wind Blade",
    grade: 1,
    type: "Air",
    description: "A basic air element killing move",
    stats: { hp: 0.1, sp: 0, str: 0.2, agl: 0.1 },
  },
  {
    name: "Gale Slash",
    grade: 2,
    type: "Air",
    description: "A decent air element killing move",
    stats: { hp: 0.2, sp: 0.1, str: 0.3, agl: 0.2 },
  },
  {
    name: "Tornado Strike",
    grade: 3,
    type: "Air",
    description: "An advanced air element killing move",
    stats: { hp: 0.3, sp: 0.2, str: 0.4, agl: 0.3 },
  },
  {
    name: "Skyfall",
    grade: 4,
    type: "Air",
    description: "An expert air element killing move",
    stats: { hp: 0.4, sp: 0.3, str: 0.5, agl: 0.4 },
  },
  {
    name: "Thunderclap",
    grade: 5,
    type: "Air",
    description: "A master-level air element killing move",
    stats: { hp: 0.5, sp: 0.4, str: 0.6, agl: 0.5 },
  },
  // Body Refinement
  {
    name: "Wind Skin",
    grade: 1,
    type: "Air",
    description: "A basic air element body forging art",
    stats: { hp: 0.3, sp: 0, str: 0.1, agl: 0 },
  },
  {
    name: "Gale Armor",
    grade: 2,
    type: "Air",
    description: "A decent air element body forging art",
    stats: { hp: 0.4, sp: 0.1, str: 0.2, agl: 0.1 },
  },
  {
    name: "Tornado Body",
    grade: 3,
    type: "Air",
    description: "An advanced air element body forging art",
    stats: { hp: 0.5, sp: 0.2, str: 0.3, agl: 0.2 },
  },
  {
    name: "Sky Essence",
    grade: 4,
    type: "Air",
    description: "An expert air element body forging art",
    stats: { hp: 0.6, sp: 0.3, str: 0.4, agl: 0.3 },
  },
  {
    name: "Cloud Core",
    grade: 5,
    type: "Air",
    description: "A master-level air element body forging art",
    stats: { hp: 0.7, sp: 0.4, str: 0.5, agl: 0.4 },
  },
  // Mind Techniques
  {
    name: "Wind Focus",
    grade: 1,
    type: "Air",
    description: "A basic air element spirit enhancing art",
    stats: { hp: 0, sp: 0.4, str: 0, agl: 0.1 },
  },
  {
    name: "Gale Mind",
    grade: 2,
    type: "Air",
    description: "A decent air element spirit enhancing art",
    stats: { hp: 0, sp: 0.6, str: 0, agl: 0.2 },
  },
  {
    name: "Tornado Wisdom",
    grade: 3,
    type: "Air",
    description: "An advanced air element spirit enhancing art",
    stats: { hp: 0, sp: 0.8, str: 0, agl: 0.3 },
  },
  {
    name: "Sky Meditation",
    grade: 4,
    type: "Air",
    description: "An expert air element spirit enhancing art",
    stats: { hp: 0, sp: 1, str: 0, agl: 0.4 },
  },
  {
    name: "Cloud Enlightenment",
    grade: 5,
    type: "Air",
    description: "A master-level air element spirit enhancing art",
    stats: { hp: 0, sp: 1.2, str: 0, agl: 0.5 },
  },
];

// None Elemental Techniques
export const NONE_ELEMENTAL_FIGHTING_TECHNIQUES = [
  //basic
  {
    name: "Basic Martial Arts",
    grade: 1,
    type: "None",
    description: "A basic none elemental fighting style",
    stats: { hp: 0.1, sp: 0.1, str: 0.1, agl: 0.1 },
  },
  // Movement Techniques
  {
    name: "Swift Step",
    grade: 1,
    type: "None",
    description: "A basic none elemental movement technique",
    stats: { hp: 0, sp: 0, str: 0.1, agl: 0.3 },
  },
  {
    name: "Quick Dash",
    grade: 2,
    type: "None",
    description: "A decent none elemental movement technique",
    stats: { hp: 0, sp: 0.1, str: 0.2, agl: 0.5 },
  },
  {
    name: "Shadow Leap",
    grade: 3,
    type: "None",
    description: "An advanced none elemental movement technique",
    stats: { hp: 0, sp: 0.2, str: 0.3, agl: 0.7 },
  },
  {
    name: "Phantom Drift",
    grade: 4,
    type: "None",
    description: "An expert none elemental movement technique",
    stats: { hp: 0, sp: 0.3, str: 0.4, agl: 0.9 },
  },
  {
    name: "Ethereal Glide",
    grade: 5,
    type: "None",
    description: "A master-level none elemental movement technique",
    stats: { hp: 0, sp: 0.4, str: 0.5, agl: 1.1 },
  },
  // Killing Moves
  {
    name: "Piercing Strike",
    grade: 1,
    type: "None",
    description: "A basic none elemental killing move",
    stats: { hp: 0.1, sp: 0, str: 0.2, agl: 0.1 },
  },
  {
    name: "Vortex Slash",
    grade: 2,
    type: "None",
    description: "A decent none elemental killing move",
    stats: { hp: 0.2, sp: 0.1, str: 0.3, agl: 0.2 },
  },
  {
    name: "Meteor Impact",
    grade: 3,
    type: "None",
    description: "An advanced none elemental killing move",
    stats: { hp: 0.3, sp: 0.2, str: 0.4, agl: 0.3 },
  },
  {
    name: "Void Annihilation",
    grade: 4,
    type: "None",
    description: "An expert none elemental killing move",
    stats: { hp: 0.4, sp: 0.3, str: 0.5, agl: 0.4 },
  },
  {
    name: "Cosmic Rupture",
    grade: 5,
    type: "None",
    description: "A master-level none elemental killing move",
    stats: { hp: 0.5, sp: 0.4, str: 0.6, agl: 0.5 },
  },
  // Body Refinement
  {
    name: "Iron Skin",
    grade: 1,
    type: "None",
    description: "A basic none elemental body forging art",
    stats: { hp: 0.3, sp: 0, str: 0.1, agl: 0 },
  },
  {
    name: "Steel Armor",
    grade: 2,
    type: "None",
    description: "A decent none elemental body forging art",
    stats: { hp: 0.4, sp: 0.1, str: 0.2, agl: 0.1 },
  },
  {
    name: "Adamantine Body",
    grade: 3,
    type: "None",
    description: "An advanced none elemental body forging art",
    stats: { hp: 0.5, sp: 0.2, str: 0.3, agl: 0.2 },
  },
  {
    name: "Titan Essence",
    grade: 4,
    type: "None",
    description: "An expert none elemental body forging art",
    stats: { hp: 0.6, sp: 0.3, str: 0.4, agl: 0.3 },
  },
  {
    name: "Celestial Core",
    grade: 5,
    type: "None",
    description: "A master-level none elemental body forging art",
    stats: { hp: 0.7, sp: 0.4, str: 0.5, agl: 0.4 },
  },
  // Mind Techniques
  {
    name: "Focused Mind",
    grade: 1,
    type: "None",
    description: "A basic none elemental spirit enhancing art",
    stats: { hp: 0, sp: 0.4, str: 0, agl: 0.1 },
  },
  {
    name: "Mental Clarity",
    grade: 2,
    type: "None",
    description: "A decent none elemental spirit enhancing art",
    stats: { hp: 0, sp: 0.6, str: 0, agl: 0.2 },
  },
  {
    name: "Soul Harmony",
    grade: 3,
    type: "None",
    description: "An advanced none elemental spirit enhancing art",
    stats: { hp: 0, sp: 0.8, str: 0, agl: 0.3 },
  },
  {
    name: "Cosmic Awareness",
    grade: 4,
    type: "None",
    description: "An expert none elemental spirit enhancing art",
    stats: { hp: 0, sp: 1, str: 0, agl: 0.4 },
  },
  {
    name: "Universal Enlightenment",
    grade: 5,
    type: "None",
    description: "A master-level none elemental spirit enhancing art",
    stats: { hp: 0, sp: 1.2, str: 0, agl: 0.5 },
  },
];

export const FIGHTING_TECHNIQUES = [
  ...AIR_FIGHTING_TECHNIQUES,
  ...EARTH_FIGHTING_TECHNIQUES,
  ...FIRE_FIGHTING_TECHNIQUES,
  ...METAL_FIGHTING_TECHNIQUES,
  ...NONE_ELEMENTAL_FIGHTING_TECHNIQUES,
  ...WATER_FIGHTING_TECHNIQUES,
  ...WOOD_FIGHTING_TECHNIQUES,
];
